### ISSUE TITLE
Could not find Cargo.toml 

### ISSUE THREAD

**Issue by soulfly** [mongodbinc-interns/mongo-rust-driver-prototype#100]
Here is my Cargo.toml

    [package]
    name = "pipe"
    version = "0.1.0"
    authors = ["Igor"]

    [dependencies.bson]
    git = "https://github.com/zonyitoo/bson-rs"

    [dependencies.mongodb]
    git = "https://github.com/mongodbinc-interns/mongo-rust-driver-prototype"

then I do 'cargo build' and receive:

    Unable to update https://github.com/mongodbinc-interns/mongo-rust-driver-prototype

    Caused by:
      Could not find Cargo.toml in `/Users/igor/.cargo/git/checkouts/mongo-rust-driver-prototype-760be1e4122dc7eb/master`

**Comment by saghm** [comment]
Looks like the issue is that Cargo defaults to checking the master branch despite the 1.0 branch being the default on our repo. If you change the entry to the following, this should work:

```
[dependencies.mongodb]
git = "https://github.com/mongodbinc-interns/mongo-rust-driver-prototype"
branch = "1.0"
```

Thanks for pointing this out! I'll update the README shortly.

**Comment by soulfly** [comment]
super fast answer!
thank you, works now
