### ISSUE TITLE
Move to use Rust 1.0

### ISSUE THREAD

**Issue by minsler** [mongodbinc-interns/mongo-rust-driver-prototype#31]

**Comment by gobwas** [comment]
:beer:

**Comment by Hokutosei** [comment]
any development going on for this to move as an official driver for rust?

**Comment by vkarpov15** [comment]
@Hokutosei just getting started over the next week or so. For now the general plan is to use the 1.0 branch for new development. We're looking for people to provide feedback on development (review PR's, etc.), because admittedly we're all pretty new to Rust. Are you interested in helping out?

**Comment by jedestep** [comment]
@vkarpov15 I would be happy to review PRs. I would also be willing to work on updating the BSON library to 1.0.

**Comment by alabid** [comment]
@jedestep Hey Jed! It'd be great if you could review some PRs.
@vkarpov15 Jed -- along with @jchinlee , another MongoDB intern at the time, created the driver for Rust 0.7
Two MongoDB interns are working on updating the Rust Driver to 1.0.

**Comment by vkarpov15** [comment]
That's great news! Always happy to have some help.

There's also another bson library out there, https://crates.io/crates/bson-rs, and we're considering just wrapping libbson using rust's libc crate. What do you think, is it worth it to upgrade the 0.7 bson library? I would imagine just wrapping libbson might be easier.

**Comment by jedestep** [comment]
Wrapping libbson will definitely be lower effort; at the time we wrote a native one to help boost up the Rust community which didn't really have many native third-party libraries. It would be neat to match the API to bson-rs so the driver is agnostic to the bson library used and end-users could compile in bson-rs if they chose.

**Comment by vkarpov15** [comment]
Actually re #41 we're planning on switching over to bson-rs because they have more rust-friendly APIs, using libbson just lead to a large mess of `unsafe` blocks everywhere and was more work than we'd like

**Comment by Byron** [comment]
It seems this issue can be closed, can it ? `bson-rs` is being used, and the project builds with Rust 1.2 stable as well.
